# 用户
user: &table
  ancestor_id: string # 祖先ID
  password: string # 密码
  nickname: string # 昵称
  family_name: string # 姓
  given_name: string # 名
  ip: string # 注册IP
  avatar: string # 头像url
---
# 认证器类型
kind:
  - account # 用户账户
  - email # 邮箱
  - phone # 手机

# 用户账户认证器
account:
  username: string # 账户名(*)
# 邮箱认证器
email:
  email: string # 邮箱(*)
# 手机认证器
phone:
  phone: string # 手机号(*)

# 认证器
authenticator: &table
  user_id: string # 用户ID
  kind: kind # 认证器类型
  anchor:  # 锚
    account: account # 用户账户认证器
    email: email # 邮箱认证器
    phone: phone # 手机认证器
