// Code generated by windranger, DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.6
// source: internal/ent/schema/authenticatorNested/authenticatorNested.proto

package authenticatorNested

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 认证器类型
type Kind int32

const (
	Kind_KIND_UNSET     Kind = 0  // 保留字：未设置
	Kind_KIND_ACCOUNT   Kind = 1  // 用户账户
	Kind_KIND_EMAIL     Kind = 2  // 邮箱
	Kind_KIND_PHONE     Kind = 3  // 手机
	Kind_KIND_GITHUB    Kind = 4  // Github
	Kind_KIND_MICROSOFT Kind = 5  // Azure AD
	Kind_KIND_CLEAR     Kind = -1 // 保留字：清空
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0:  "KIND_UNSET",
		1:  "KIND_ACCOUNT",
		2:  "KIND_EMAIL",
		3:  "KIND_PHONE",
		4:  "KIND_GITHUB",
		5:  "KIND_MICROSOFT",
		-1: "KIND_CLEAR",
	}
	Kind_value = map[string]int32{
		"KIND_UNSET":     0,
		"KIND_ACCOUNT":   1,
		"KIND_EMAIL":     2,
		"KIND_PHONE":     3,
		"KIND_GITHUB":    4,
		"KIND_MICROSOFT": 5,
		"KIND_CLEAR":     -1,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{0}
}

// 认证器
type Authenticator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                    // 主键
	UserId *string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`              // 用户ID
	Kind   *Kind   `protobuf:"varint,3,opt,name=kind,proto3,enum=authenticatorNested.Kind,oneof" json:"kind,omitempty"` // 认证器类型
	Unique *Unique `protobuf:"bytes,4,opt,name=unique,proto3,oneof" json:"unique,omitempty"`                            // 唯一值
}

func (x *Authenticator) Reset() {
	*x = Authenticator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authenticator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator) ProtoMessage() {}

func (x *Authenticator) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator.ProtoReflect.Descriptor instead.
func (*Authenticator) Descriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{0}
}

func (x *Authenticator) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Authenticator) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Authenticator) GetKind() Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Kind_KIND_UNSET
}

func (x *Authenticator) GetUnique() *Unique {
	if x != nil {
		return x.Unique
	}
	return nil
}

// 唯一值
type Unique struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   *string `protobuf:"bytes,1,opt,name=account,proto3,oneof" json:"account,omitempty"`     // 用户账户
	Email     *string `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`         // 邮箱
	Phone     *string `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`         // 手机
	Github    *int64  `protobuf:"varint,4,opt,name=github,proto3,oneof" json:"github,omitempty"`      // Github
	Microsoft *string `protobuf:"bytes,5,opt,name=microsoft,proto3,oneof" json:"microsoft,omitempty"` // Azure AD
}

func (x *Unique) Reset() {
	*x = Unique{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unique) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unique) ProtoMessage() {}

func (x *Unique) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unique.ProtoReflect.Descriptor instead.
func (*Unique) Descriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{1}
}

func (x *Unique) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *Unique) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Unique) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Unique) GetGithub() int64 {
	if x != nil && x.Github != nil {
		return *x.Github
	}
	return 0
}

func (x *Unique) GetMicrosoft() string {
	if x != nil && x.Microsoft != nil {
		return *x.Microsoft
	}
	return ""
}

var File_internal_ent_schema_authenticatorNested_authenticatorNested_proto protoreflect.FileDescriptor

var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDesc = []byte{
	0x0a, 0x41, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x6e, 0x74, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x0d, 0x41, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12,
	0x1c, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x48, 0x02, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x38, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f,
	0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x48, 0x03,
	0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f,
	0x69, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x75, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x1d, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x03, 0x52, 0x06, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x88, 0x01, 0x01, 0x12,
	0x21, 0x0a, 0x09, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x04, 0x52, 0x09, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2a, 0x86, 0x01, 0x0a, 0x04,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53,
	0x45, 0x54, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x41, 0x43, 0x43,
	0x4f, 0x55, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x45,
	0x4d, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x50,
	0x48, 0x4f, 0x4e, 0x45, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x47,
	0x49, 0x54, 0x48, 0x55, 0x42, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x4d, 0x49, 0x43, 0x52, 0x4f, 0x53, 0x4f, 0x46, 0x54, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x0a, 0x4b,
	0x49, 0x4e, 0x44, 0x5f, 0x43, 0x4c, 0x45, 0x41, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0x01, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x77, 0x7a, 0x79, 0x6a, 0x65, 0x72, 0x72, 0x79, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescOnce sync.Once
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescData = file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDesc
)

func file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP() []byte {
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescOnce.Do(func() {
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescData)
	})
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescData
}

var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_goTypes = []interface{}{
	(Kind)(0),             // 0: authenticatorNested.Kind
	(*Authenticator)(nil), // 1: authenticatorNested.Authenticator
	(*Unique)(nil),        // 2: authenticatorNested.Unique
}
var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_depIdxs = []int32{
	0, // 0: authenticatorNested.Authenticator.kind:type_name -> authenticatorNested.Kind
	2, // 1: authenticatorNested.Authenticator.unique:type_name -> authenticatorNested.Unique
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_init() }
func file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_init() {
	if File_internal_ent_schema_authenticatorNested_authenticatorNested_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authenticator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unique); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_goTypes,
		DependencyIndexes: file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_depIdxs,
		EnumInfos:         file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_enumTypes,
		MessageInfos:      file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes,
	}.Build()
	File_internal_ent_schema_authenticatorNested_authenticatorNested_proto = out.File
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDesc = nil
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_goTypes = nil
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_depIdxs = nil
}
