// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wzyjerry/auth/internal/ent/authenticator"
	"github.com/wzyjerry/auth/internal/ent/predicate"
	"github.com/wzyjerry/auth/internal/ent/schema/authenticatorNested"
)

// AuthenticatorUpdate is the builder for updating Authenticator entities.
type AuthenticatorUpdate struct {
	config
	hooks    []Hook
	mutation *AuthenticatorMutation
}

// Where appends a list predicates to the AuthenticatorUpdate builder.
func (au *AuthenticatorUpdate) Where(ps ...predicate.Authenticator) *AuthenticatorUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUserID sets the "user_id" field.
func (au *AuthenticatorUpdate) SetUserID(s string) *AuthenticatorUpdate {
	au.mutation.SetUserID(s)
	return au
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (au *AuthenticatorUpdate) SetNillableUserID(s *string) *AuthenticatorUpdate {
	if s != nil {
		au.SetUserID(*s)
	}
	return au
}

// ClearUserID clears the value of the "user_id" field.
func (au *AuthenticatorUpdate) ClearUserID() *AuthenticatorUpdate {
	au.mutation.ClearUserID()
	return au
}

// SetKind sets the "kind" field.
func (au *AuthenticatorUpdate) SetKind(i int32) *AuthenticatorUpdate {
	au.mutation.ResetKind()
	au.mutation.SetKind(i)
	return au
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (au *AuthenticatorUpdate) SetNillableKind(i *int32) *AuthenticatorUpdate {
	if i != nil {
		au.SetKind(*i)
	}
	return au
}

// AddKind adds i to the "kind" field.
func (au *AuthenticatorUpdate) AddKind(i int32) *AuthenticatorUpdate {
	au.mutation.AddKind(i)
	return au
}

// ClearKind clears the value of the "kind" field.
func (au *AuthenticatorUpdate) ClearKind() *AuthenticatorUpdate {
	au.mutation.ClearKind()
	return au
}

// SetAnchor sets the "anchor" field.
func (au *AuthenticatorUpdate) SetAnchor(an *authenticatorNested.Anchor) *AuthenticatorUpdate {
	au.mutation.SetAnchor(an)
	return au
}

// ClearAnchor clears the value of the "anchor" field.
func (au *AuthenticatorUpdate) ClearAnchor() *AuthenticatorUpdate {
	au.mutation.ClearAnchor()
	return au
}

// Mutation returns the AuthenticatorMutation object of the builder.
func (au *AuthenticatorUpdate) Mutation() *AuthenticatorMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AuthenticatorUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthenticatorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AuthenticatorUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AuthenticatorUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AuthenticatorUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AuthenticatorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   authenticator.Table,
			Columns: authenticator.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: authenticator.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: authenticator.FieldUserID,
		})
	}
	if au.mutation.UserIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: authenticator.FieldUserID,
		})
	}
	if value, ok := au.mutation.Kind(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: authenticator.FieldKind,
		})
	}
	if value, ok := au.mutation.AddedKind(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: authenticator.FieldKind,
		})
	}
	if au.mutation.KindCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: authenticator.FieldKind,
		})
	}
	if value, ok := au.mutation.Anchor(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: authenticator.FieldAnchor,
		})
	}
	if au.mutation.AnchorCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: authenticator.FieldAnchor,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authenticator.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AuthenticatorUpdateOne is the builder for updating a single Authenticator entity.
type AuthenticatorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthenticatorMutation
}

// SetUserID sets the "user_id" field.
func (auo *AuthenticatorUpdateOne) SetUserID(s string) *AuthenticatorUpdateOne {
	auo.mutation.SetUserID(s)
	return auo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (auo *AuthenticatorUpdateOne) SetNillableUserID(s *string) *AuthenticatorUpdateOne {
	if s != nil {
		auo.SetUserID(*s)
	}
	return auo
}

// ClearUserID clears the value of the "user_id" field.
func (auo *AuthenticatorUpdateOne) ClearUserID() *AuthenticatorUpdateOne {
	auo.mutation.ClearUserID()
	return auo
}

// SetKind sets the "kind" field.
func (auo *AuthenticatorUpdateOne) SetKind(i int32) *AuthenticatorUpdateOne {
	auo.mutation.ResetKind()
	auo.mutation.SetKind(i)
	return auo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (auo *AuthenticatorUpdateOne) SetNillableKind(i *int32) *AuthenticatorUpdateOne {
	if i != nil {
		auo.SetKind(*i)
	}
	return auo
}

// AddKind adds i to the "kind" field.
func (auo *AuthenticatorUpdateOne) AddKind(i int32) *AuthenticatorUpdateOne {
	auo.mutation.AddKind(i)
	return auo
}

// ClearKind clears the value of the "kind" field.
func (auo *AuthenticatorUpdateOne) ClearKind() *AuthenticatorUpdateOne {
	auo.mutation.ClearKind()
	return auo
}

// SetAnchor sets the "anchor" field.
func (auo *AuthenticatorUpdateOne) SetAnchor(an *authenticatorNested.Anchor) *AuthenticatorUpdateOne {
	auo.mutation.SetAnchor(an)
	return auo
}

// ClearAnchor clears the value of the "anchor" field.
func (auo *AuthenticatorUpdateOne) ClearAnchor() *AuthenticatorUpdateOne {
	auo.mutation.ClearAnchor()
	return auo
}

// Mutation returns the AuthenticatorMutation object of the builder.
func (auo *AuthenticatorUpdateOne) Mutation() *AuthenticatorMutation {
	return auo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AuthenticatorUpdateOne) Select(field string, fields ...string) *AuthenticatorUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Authenticator entity.
func (auo *AuthenticatorUpdateOne) Save(ctx context.Context) (*Authenticator, error) {
	var (
		err  error
		node *Authenticator
	)
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthenticatorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AuthenticatorUpdateOne) SaveX(ctx context.Context) *Authenticator {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AuthenticatorUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AuthenticatorUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AuthenticatorUpdateOne) sqlSave(ctx context.Context) (_node *Authenticator, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   authenticator.Table,
			Columns: authenticator.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: authenticator.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Authenticator.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authenticator.FieldID)
		for _, f := range fields {
			if !authenticator.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authenticator.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: authenticator.FieldUserID,
		})
	}
	if auo.mutation.UserIDCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: authenticator.FieldUserID,
		})
	}
	if value, ok := auo.mutation.Kind(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: authenticator.FieldKind,
		})
	}
	if value, ok := auo.mutation.AddedKind(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: authenticator.FieldKind,
		})
	}
	if auo.mutation.KindCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Column: authenticator.FieldKind,
		})
	}
	if value, ok := auo.mutation.Anchor(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: authenticator.FieldAnchor,
		})
	}
	if auo.mutation.AnchorCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: authenticator.FieldAnchor,
		})
	}
	_node = &Authenticator{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authenticator.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
