// Code generated by windranger, DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.6
// source: internal/ent/schema/avatarNested/avatarNested.proto

package avatarNested

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 头像类型
type Kind int32

const (
	Kind_KIND_UNSET       Kind = 0  // 保留字：未设置
	Kind_KIND_USER        Kind = 1  // 用户头像
	Kind_KIND_APPLICATION Kind = 2  // 应用Logo
	Kind_KIND_CLEAR       Kind = -1 // 保留字：清空
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0:  "KIND_UNSET",
		1:  "KIND_USER",
		2:  "KIND_APPLICATION",
		-1: "KIND_CLEAR",
	}
	Kind_value = map[string]int32{
		"KIND_UNSET":       0,
		"KIND_USER":        1,
		"KIND_APPLICATION": 2,
		"KIND_CLEAR":       -1,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_ent_schema_avatarNested_avatarNested_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_internal_ent_schema_avatarNested_avatarNested_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescGZIP(), []int{0}
}

// 头像
type Avatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                             // 主键
	Kind   *Kind   `protobuf:"varint,2,opt,name=kind,proto3,enum=avatarNested.Kind,oneof" json:"kind,omitempty"` // 头像类型
	RelId  *string `protobuf:"bytes,3,opt,name=rel_id,json=relId,proto3,oneof" json:"rel_id,omitempty"`          // 关联ID
	Avatar *string `protobuf:"bytes,4,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`                     // 头像base64串
}

func (x *Avatar) Reset() {
	*x = Avatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ent_schema_avatarNested_avatarNested_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Avatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avatar) ProtoMessage() {}

func (x *Avatar) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ent_schema_avatarNested_avatarNested_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avatar.ProtoReflect.Descriptor instead.
func (*Avatar) Descriptor() ([]byte, []int) {
	return file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescGZIP(), []int{0}
}

func (x *Avatar) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Avatar) GetKind() Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Kind_KIND_UNSET
}

func (x *Avatar) GetRelId() string {
	if x != nil && x.RelId != nil {
		return *x.RelId
	}
	return ""
}

func (x *Avatar) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

var File_internal_ent_schema_avatarNested_avatarNested_proto protoreflect.FileDescriptor

var file_internal_ent_schema_avatarNested_avatarNested_proto_rawDesc = []byte{
	0x0a, 0x33, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x6e, 0x74, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x2f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x22, 0xa9, 0x01, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x13,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x48, 0x01, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x1a, 0x0a, 0x06, 0x72, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65,
	0x6c, 0x5f, 0x69, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2a,
	0x54, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x41,
	0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x0a,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x43, 0x4c, 0x45, 0x41, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0x01, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x7a, 0x79, 0x6a, 0x65, 0x72, 0x72, 0x79, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x6e, 0x74, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescOnce sync.Once
	file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescData = file_internal_ent_schema_avatarNested_avatarNested_proto_rawDesc
)

func file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescGZIP() []byte {
	file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescOnce.Do(func() {
		file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescData)
	})
	return file_internal_ent_schema_avatarNested_avatarNested_proto_rawDescData
}

var file_internal_ent_schema_avatarNested_avatarNested_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_ent_schema_avatarNested_avatarNested_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_ent_schema_avatarNested_avatarNested_proto_goTypes = []interface{}{
	(Kind)(0),      // 0: avatarNested.Kind
	(*Avatar)(nil), // 1: avatarNested.Avatar
}
var file_internal_ent_schema_avatarNested_avatarNested_proto_depIdxs = []int32{
	0, // 0: avatarNested.Avatar.kind:type_name -> avatarNested.Kind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_ent_schema_avatarNested_avatarNested_proto_init() }
func file_internal_ent_schema_avatarNested_avatarNested_proto_init() {
	if File_internal_ent_schema_avatarNested_avatarNested_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_ent_schema_avatarNested_avatarNested_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Avatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_ent_schema_avatarNested_avatarNested_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ent_schema_avatarNested_avatarNested_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ent_schema_avatarNested_avatarNested_proto_goTypes,
		DependencyIndexes: file_internal_ent_schema_avatarNested_avatarNested_proto_depIdxs,
		EnumInfos:         file_internal_ent_schema_avatarNested_avatarNested_proto_enumTypes,
		MessageInfos:      file_internal_ent_schema_avatarNested_avatarNested_proto_msgTypes,
	}.Build()
	File_internal_ent_schema_avatarNested_avatarNested_proto = out.File
	file_internal_ent_schema_avatarNested_avatarNested_proto_rawDesc = nil
	file_internal_ent_schema_avatarNested_avatarNested_proto_goTypes = nil
	file_internal_ent_schema_avatarNested_avatarNested_proto_depIdxs = nil
}
