// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/wzyjerry/auth/internal/ent/application"
	"github.com/wzyjerry/auth/internal/ent/authenticator"
	"github.com/wzyjerry/auth/internal/ent/avatar"
	"github.com/wzyjerry/auth/internal/ent/predicate"
	"github.com/wzyjerry/auth/internal/ent/schema/applicationNested"
	"github.com/wzyjerry/auth/internal/ent/schema/authenticatorNested"
	"github.com/wzyjerry/auth/internal/ent/user"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeApplication   = "Application"
	TypeAuthenticator = "Authenticator"
	TypeAvatar        = "Avatar"
	TypeUser          = "User"
)

// ApplicationMutation represents an operation that mutates the Application nodes in the graph.
type ApplicationMutation struct {
	config
	op             Op
	typ            string
	id             *string
	name           *string
	homepage       *string
	description    *string
	callback       *string
	admin          *string
	client_id      *string
	client_secrets *[]*applicationNested.ClientSecret
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*Application, error)
	predicates     []predicate.Application
}

var _ ent.Mutation = (*ApplicationMutation)(nil)

// applicationOption allows management of the mutation configuration using functional options.
type applicationOption func(*ApplicationMutation)

// newApplicationMutation creates new mutation for the Application entity.
func newApplicationMutation(c config, op Op, opts ...applicationOption) *ApplicationMutation {
	m := &ApplicationMutation{
		config:        c,
		op:            op,
		typ:           TypeApplication,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withApplicationID sets the ID field of the mutation.
func withApplicationID(id string) applicationOption {
	return func(m *ApplicationMutation) {
		var (
			err   error
			once  sync.Once
			value *Application
		)
		m.oldValue = func(ctx context.Context) (*Application, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Application.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withApplication sets the old Application of the mutation.
func withApplication(node *Application) applicationOption {
	return func(m *ApplicationMutation) {
		m.oldValue = func(context.Context) (*Application, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ApplicationMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ApplicationMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Application entities.
func (m *ApplicationMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ApplicationMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ApplicationMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Application.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ApplicationMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ApplicationMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Application entity.
// If the Application object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApplicationMutation) OldName(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ClearName clears the value of the "name" field.
func (m *ApplicationMutation) ClearName() {
	m.name = nil
	m.clearedFields[application.FieldName] = struct{}{}
}

// NameCleared returns if the "name" field was cleared in this mutation.
func (m *ApplicationMutation) NameCleared() bool {
	_, ok := m.clearedFields[application.FieldName]
	return ok
}

// ResetName resets all changes to the "name" field.
func (m *ApplicationMutation) ResetName() {
	m.name = nil
	delete(m.clearedFields, application.FieldName)
}

// SetHomepage sets the "homepage" field.
func (m *ApplicationMutation) SetHomepage(s string) {
	m.homepage = &s
}

// Homepage returns the value of the "homepage" field in the mutation.
func (m *ApplicationMutation) Homepage() (r string, exists bool) {
	v := m.homepage
	if v == nil {
		return
	}
	return *v, true
}

// OldHomepage returns the old "homepage" field's value of the Application entity.
// If the Application object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApplicationMutation) OldHomepage(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHomepage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHomepage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHomepage: %w", err)
	}
	return oldValue.Homepage, nil
}

// ClearHomepage clears the value of the "homepage" field.
func (m *ApplicationMutation) ClearHomepage() {
	m.homepage = nil
	m.clearedFields[application.FieldHomepage] = struct{}{}
}

// HomepageCleared returns if the "homepage" field was cleared in this mutation.
func (m *ApplicationMutation) HomepageCleared() bool {
	_, ok := m.clearedFields[application.FieldHomepage]
	return ok
}

// ResetHomepage resets all changes to the "homepage" field.
func (m *ApplicationMutation) ResetHomepage() {
	m.homepage = nil
	delete(m.clearedFields, application.FieldHomepage)
}

// SetDescription sets the "description" field.
func (m *ApplicationMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *ApplicationMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Application entity.
// If the Application object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApplicationMutation) OldDescription(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *ApplicationMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[application.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *ApplicationMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[application.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *ApplicationMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, application.FieldDescription)
}

// SetCallback sets the "callback" field.
func (m *ApplicationMutation) SetCallback(s string) {
	m.callback = &s
}

// Callback returns the value of the "callback" field in the mutation.
func (m *ApplicationMutation) Callback() (r string, exists bool) {
	v := m.callback
	if v == nil {
		return
	}
	return *v, true
}

// OldCallback returns the old "callback" field's value of the Application entity.
// If the Application object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApplicationMutation) OldCallback(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCallback is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCallback requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCallback: %w", err)
	}
	return oldValue.Callback, nil
}

// ClearCallback clears the value of the "callback" field.
func (m *ApplicationMutation) ClearCallback() {
	m.callback = nil
	m.clearedFields[application.FieldCallback] = struct{}{}
}

// CallbackCleared returns if the "callback" field was cleared in this mutation.
func (m *ApplicationMutation) CallbackCleared() bool {
	_, ok := m.clearedFields[application.FieldCallback]
	return ok
}

// ResetCallback resets all changes to the "callback" field.
func (m *ApplicationMutation) ResetCallback() {
	m.callback = nil
	delete(m.clearedFields, application.FieldCallback)
}

// SetAdmin sets the "admin" field.
func (m *ApplicationMutation) SetAdmin(s string) {
	m.admin = &s
}

// Admin returns the value of the "admin" field in the mutation.
func (m *ApplicationMutation) Admin() (r string, exists bool) {
	v := m.admin
	if v == nil {
		return
	}
	return *v, true
}

// OldAdmin returns the old "admin" field's value of the Application entity.
// If the Application object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApplicationMutation) OldAdmin(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAdmin is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAdmin requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAdmin: %w", err)
	}
	return oldValue.Admin, nil
}

// ClearAdmin clears the value of the "admin" field.
func (m *ApplicationMutation) ClearAdmin() {
	m.admin = nil
	m.clearedFields[application.FieldAdmin] = struct{}{}
}

// AdminCleared returns if the "admin" field was cleared in this mutation.
func (m *ApplicationMutation) AdminCleared() bool {
	_, ok := m.clearedFields[application.FieldAdmin]
	return ok
}

// ResetAdmin resets all changes to the "admin" field.
func (m *ApplicationMutation) ResetAdmin() {
	m.admin = nil
	delete(m.clearedFields, application.FieldAdmin)
}

// SetClientID sets the "client_id" field.
func (m *ApplicationMutation) SetClientID(s string) {
	m.client_id = &s
}

// ClientID returns the value of the "client_id" field in the mutation.
func (m *ApplicationMutation) ClientID() (r string, exists bool) {
	v := m.client_id
	if v == nil {
		return
	}
	return *v, true
}

// OldClientID returns the old "client_id" field's value of the Application entity.
// If the Application object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApplicationMutation) OldClientID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClientID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClientID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClientID: %w", err)
	}
	return oldValue.ClientID, nil
}

// ClearClientID clears the value of the "client_id" field.
func (m *ApplicationMutation) ClearClientID() {
	m.client_id = nil
	m.clearedFields[application.FieldClientID] = struct{}{}
}

// ClientIDCleared returns if the "client_id" field was cleared in this mutation.
func (m *ApplicationMutation) ClientIDCleared() bool {
	_, ok := m.clearedFields[application.FieldClientID]
	return ok
}

// ResetClientID resets all changes to the "client_id" field.
func (m *ApplicationMutation) ResetClientID() {
	m.client_id = nil
	delete(m.clearedFields, application.FieldClientID)
}

// SetClientSecrets sets the "client_secrets" field.
func (m *ApplicationMutation) SetClientSecrets(ans []*applicationNested.ClientSecret) {
	m.client_secrets = &ans
}

// ClientSecrets returns the value of the "client_secrets" field in the mutation.
func (m *ApplicationMutation) ClientSecrets() (r []*applicationNested.ClientSecret, exists bool) {
	v := m.client_secrets
	if v == nil {
		return
	}
	return *v, true
}

// OldClientSecrets returns the old "client_secrets" field's value of the Application entity.
// If the Application object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ApplicationMutation) OldClientSecrets(ctx context.Context) (v []*applicationNested.ClientSecret, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClientSecrets is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClientSecrets requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClientSecrets: %w", err)
	}
	return oldValue.ClientSecrets, nil
}

// ClearClientSecrets clears the value of the "client_secrets" field.
func (m *ApplicationMutation) ClearClientSecrets() {
	m.client_secrets = nil
	m.clearedFields[application.FieldClientSecrets] = struct{}{}
}

// ClientSecretsCleared returns if the "client_secrets" field was cleared in this mutation.
func (m *ApplicationMutation) ClientSecretsCleared() bool {
	_, ok := m.clearedFields[application.FieldClientSecrets]
	return ok
}

// ResetClientSecrets resets all changes to the "client_secrets" field.
func (m *ApplicationMutation) ResetClientSecrets() {
	m.client_secrets = nil
	delete(m.clearedFields, application.FieldClientSecrets)
}

// Where appends a list predicates to the ApplicationMutation builder.
func (m *ApplicationMutation) Where(ps ...predicate.Application) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *ApplicationMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Application).
func (m *ApplicationMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ApplicationMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.name != nil {
		fields = append(fields, application.FieldName)
	}
	if m.homepage != nil {
		fields = append(fields, application.FieldHomepage)
	}
	if m.description != nil {
		fields = append(fields, application.FieldDescription)
	}
	if m.callback != nil {
		fields = append(fields, application.FieldCallback)
	}
	if m.admin != nil {
		fields = append(fields, application.FieldAdmin)
	}
	if m.client_id != nil {
		fields = append(fields, application.FieldClientID)
	}
	if m.client_secrets != nil {
		fields = append(fields, application.FieldClientSecrets)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ApplicationMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case application.FieldName:
		return m.Name()
	case application.FieldHomepage:
		return m.Homepage()
	case application.FieldDescription:
		return m.Description()
	case application.FieldCallback:
		return m.Callback()
	case application.FieldAdmin:
		return m.Admin()
	case application.FieldClientID:
		return m.ClientID()
	case application.FieldClientSecrets:
		return m.ClientSecrets()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ApplicationMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case application.FieldName:
		return m.OldName(ctx)
	case application.FieldHomepage:
		return m.OldHomepage(ctx)
	case application.FieldDescription:
		return m.OldDescription(ctx)
	case application.FieldCallback:
		return m.OldCallback(ctx)
	case application.FieldAdmin:
		return m.OldAdmin(ctx)
	case application.FieldClientID:
		return m.OldClientID(ctx)
	case application.FieldClientSecrets:
		return m.OldClientSecrets(ctx)
	}
	return nil, fmt.Errorf("unknown Application field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ApplicationMutation) SetField(name string, value ent.Value) error {
	switch name {
	case application.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case application.FieldHomepage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHomepage(v)
		return nil
	case application.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case application.FieldCallback:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCallback(v)
		return nil
	case application.FieldAdmin:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAdmin(v)
		return nil
	case application.FieldClientID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClientID(v)
		return nil
	case application.FieldClientSecrets:
		v, ok := value.([]*applicationNested.ClientSecret)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClientSecrets(v)
		return nil
	}
	return fmt.Errorf("unknown Application field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ApplicationMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ApplicationMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ApplicationMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Application numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ApplicationMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(application.FieldName) {
		fields = append(fields, application.FieldName)
	}
	if m.FieldCleared(application.FieldHomepage) {
		fields = append(fields, application.FieldHomepage)
	}
	if m.FieldCleared(application.FieldDescription) {
		fields = append(fields, application.FieldDescription)
	}
	if m.FieldCleared(application.FieldCallback) {
		fields = append(fields, application.FieldCallback)
	}
	if m.FieldCleared(application.FieldAdmin) {
		fields = append(fields, application.FieldAdmin)
	}
	if m.FieldCleared(application.FieldClientID) {
		fields = append(fields, application.FieldClientID)
	}
	if m.FieldCleared(application.FieldClientSecrets) {
		fields = append(fields, application.FieldClientSecrets)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ApplicationMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ApplicationMutation) ClearField(name string) error {
	switch name {
	case application.FieldName:
		m.ClearName()
		return nil
	case application.FieldHomepage:
		m.ClearHomepage()
		return nil
	case application.FieldDescription:
		m.ClearDescription()
		return nil
	case application.FieldCallback:
		m.ClearCallback()
		return nil
	case application.FieldAdmin:
		m.ClearAdmin()
		return nil
	case application.FieldClientID:
		m.ClearClientID()
		return nil
	case application.FieldClientSecrets:
		m.ClearClientSecrets()
		return nil
	}
	return fmt.Errorf("unknown Application nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ApplicationMutation) ResetField(name string) error {
	switch name {
	case application.FieldName:
		m.ResetName()
		return nil
	case application.FieldHomepage:
		m.ResetHomepage()
		return nil
	case application.FieldDescription:
		m.ResetDescription()
		return nil
	case application.FieldCallback:
		m.ResetCallback()
		return nil
	case application.FieldAdmin:
		m.ResetAdmin()
		return nil
	case application.FieldClientID:
		m.ResetClientID()
		return nil
	case application.FieldClientSecrets:
		m.ResetClientSecrets()
		return nil
	}
	return fmt.Errorf("unknown Application field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ApplicationMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ApplicationMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ApplicationMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ApplicationMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ApplicationMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ApplicationMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ApplicationMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Application unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ApplicationMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Application edge %s", name)
}

// AuthenticatorMutation represents an operation that mutates the Authenticator nodes in the graph.
type AuthenticatorMutation struct {
	config
	op            Op
	typ           string
	id            *string
	user_id       *string
	kind          *int32
	addkind       *int32
	_unique       **authenticatorNested.Unique
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Authenticator, error)
	predicates    []predicate.Authenticator
}

var _ ent.Mutation = (*AuthenticatorMutation)(nil)

// authenticatorOption allows management of the mutation configuration using functional options.
type authenticatorOption func(*AuthenticatorMutation)

// newAuthenticatorMutation creates new mutation for the Authenticator entity.
func newAuthenticatorMutation(c config, op Op, opts ...authenticatorOption) *AuthenticatorMutation {
	m := &AuthenticatorMutation{
		config:        c,
		op:            op,
		typ:           TypeAuthenticator,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAuthenticatorID sets the ID field of the mutation.
func withAuthenticatorID(id string) authenticatorOption {
	return func(m *AuthenticatorMutation) {
		var (
			err   error
			once  sync.Once
			value *Authenticator
		)
		m.oldValue = func(ctx context.Context) (*Authenticator, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Authenticator.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAuthenticator sets the old Authenticator of the mutation.
func withAuthenticator(node *Authenticator) authenticatorOption {
	return func(m *AuthenticatorMutation) {
		m.oldValue = func(context.Context) (*Authenticator, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AuthenticatorMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AuthenticatorMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Authenticator entities.
func (m *AuthenticatorMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AuthenticatorMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AuthenticatorMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Authenticator.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserID sets the "user_id" field.
func (m *AuthenticatorMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *AuthenticatorMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the Authenticator entity.
// If the Authenticator object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuthenticatorMutation) OldUserID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ClearUserID clears the value of the "user_id" field.
func (m *AuthenticatorMutation) ClearUserID() {
	m.user_id = nil
	m.clearedFields[authenticator.FieldUserID] = struct{}{}
}

// UserIDCleared returns if the "user_id" field was cleared in this mutation.
func (m *AuthenticatorMutation) UserIDCleared() bool {
	_, ok := m.clearedFields[authenticator.FieldUserID]
	return ok
}

// ResetUserID resets all changes to the "user_id" field.
func (m *AuthenticatorMutation) ResetUserID() {
	m.user_id = nil
	delete(m.clearedFields, authenticator.FieldUserID)
}

// SetKind sets the "kind" field.
func (m *AuthenticatorMutation) SetKind(i int32) {
	m.kind = &i
	m.addkind = nil
}

// Kind returns the value of the "kind" field in the mutation.
func (m *AuthenticatorMutation) Kind() (r int32, exists bool) {
	v := m.kind
	if v == nil {
		return
	}
	return *v, true
}

// OldKind returns the old "kind" field's value of the Authenticator entity.
// If the Authenticator object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuthenticatorMutation) OldKind(ctx context.Context) (v *int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKind is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKind requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKind: %w", err)
	}
	return oldValue.Kind, nil
}

// AddKind adds i to the "kind" field.
func (m *AuthenticatorMutation) AddKind(i int32) {
	if m.addkind != nil {
		*m.addkind += i
	} else {
		m.addkind = &i
	}
}

// AddedKind returns the value that was added to the "kind" field in this mutation.
func (m *AuthenticatorMutation) AddedKind() (r int32, exists bool) {
	v := m.addkind
	if v == nil {
		return
	}
	return *v, true
}

// ClearKind clears the value of the "kind" field.
func (m *AuthenticatorMutation) ClearKind() {
	m.kind = nil
	m.addkind = nil
	m.clearedFields[authenticator.FieldKind] = struct{}{}
}

// KindCleared returns if the "kind" field was cleared in this mutation.
func (m *AuthenticatorMutation) KindCleared() bool {
	_, ok := m.clearedFields[authenticator.FieldKind]
	return ok
}

// ResetKind resets all changes to the "kind" field.
func (m *AuthenticatorMutation) ResetKind() {
	m.kind = nil
	m.addkind = nil
	delete(m.clearedFields, authenticator.FieldKind)
}

// SetUnique sets the "unique" field.
func (m *AuthenticatorMutation) SetUnique(an *authenticatorNested.Unique) {
	m._unique = &an
}

// Unique returns the value of the "unique" field in the mutation.
func (m *AuthenticatorMutation) Unique() (r *authenticatorNested.Unique, exists bool) {
	v := m._unique
	if v == nil {
		return
	}
	return *v, true
}

// OldUnique returns the old "unique" field's value of the Authenticator entity.
// If the Authenticator object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuthenticatorMutation) OldUnique(ctx context.Context) (v *authenticatorNested.Unique, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUnique is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUnique requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUnique: %w", err)
	}
	return oldValue.Unique, nil
}

// ClearUnique clears the value of the "unique" field.
func (m *AuthenticatorMutation) ClearUnique() {
	m._unique = nil
	m.clearedFields[authenticator.FieldUnique] = struct{}{}
}

// UniqueCleared returns if the "unique" field was cleared in this mutation.
func (m *AuthenticatorMutation) UniqueCleared() bool {
	_, ok := m.clearedFields[authenticator.FieldUnique]
	return ok
}

// ResetUnique resets all changes to the "unique" field.
func (m *AuthenticatorMutation) ResetUnique() {
	m._unique = nil
	delete(m.clearedFields, authenticator.FieldUnique)
}

// Where appends a list predicates to the AuthenticatorMutation builder.
func (m *AuthenticatorMutation) Where(ps ...predicate.Authenticator) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *AuthenticatorMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Authenticator).
func (m *AuthenticatorMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AuthenticatorMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.user_id != nil {
		fields = append(fields, authenticator.FieldUserID)
	}
	if m.kind != nil {
		fields = append(fields, authenticator.FieldKind)
	}
	if m._unique != nil {
		fields = append(fields, authenticator.FieldUnique)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AuthenticatorMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case authenticator.FieldUserID:
		return m.UserID()
	case authenticator.FieldKind:
		return m.Kind()
	case authenticator.FieldUnique:
		return m.Unique()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AuthenticatorMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case authenticator.FieldUserID:
		return m.OldUserID(ctx)
	case authenticator.FieldKind:
		return m.OldKind(ctx)
	case authenticator.FieldUnique:
		return m.OldUnique(ctx)
	}
	return nil, fmt.Errorf("unknown Authenticator field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuthenticatorMutation) SetField(name string, value ent.Value) error {
	switch name {
	case authenticator.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case authenticator.FieldKind:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKind(v)
		return nil
	case authenticator.FieldUnique:
		v, ok := value.(*authenticatorNested.Unique)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUnique(v)
		return nil
	}
	return fmt.Errorf("unknown Authenticator field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AuthenticatorMutation) AddedFields() []string {
	var fields []string
	if m.addkind != nil {
		fields = append(fields, authenticator.FieldKind)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AuthenticatorMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case authenticator.FieldKind:
		return m.AddedKind()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuthenticatorMutation) AddField(name string, value ent.Value) error {
	switch name {
	case authenticator.FieldKind:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddKind(v)
		return nil
	}
	return fmt.Errorf("unknown Authenticator numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AuthenticatorMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(authenticator.FieldUserID) {
		fields = append(fields, authenticator.FieldUserID)
	}
	if m.FieldCleared(authenticator.FieldKind) {
		fields = append(fields, authenticator.FieldKind)
	}
	if m.FieldCleared(authenticator.FieldUnique) {
		fields = append(fields, authenticator.FieldUnique)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AuthenticatorMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AuthenticatorMutation) ClearField(name string) error {
	switch name {
	case authenticator.FieldUserID:
		m.ClearUserID()
		return nil
	case authenticator.FieldKind:
		m.ClearKind()
		return nil
	case authenticator.FieldUnique:
		m.ClearUnique()
		return nil
	}
	return fmt.Errorf("unknown Authenticator nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AuthenticatorMutation) ResetField(name string) error {
	switch name {
	case authenticator.FieldUserID:
		m.ResetUserID()
		return nil
	case authenticator.FieldKind:
		m.ResetKind()
		return nil
	case authenticator.FieldUnique:
		m.ResetUnique()
		return nil
	}
	return fmt.Errorf("unknown Authenticator field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AuthenticatorMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AuthenticatorMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AuthenticatorMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AuthenticatorMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AuthenticatorMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AuthenticatorMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AuthenticatorMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Authenticator unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AuthenticatorMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Authenticator edge %s", name)
}

// AvatarMutation represents an operation that mutates the Avatar nodes in the graph.
type AvatarMutation struct {
	config
	op            Op
	typ           string
	id            *string
	kind          *int32
	addkind       *int32
	rel_id        *string
	avatar        *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Avatar, error)
	predicates    []predicate.Avatar
}

var _ ent.Mutation = (*AvatarMutation)(nil)

// avatarOption allows management of the mutation configuration using functional options.
type avatarOption func(*AvatarMutation)

// newAvatarMutation creates new mutation for the Avatar entity.
func newAvatarMutation(c config, op Op, opts ...avatarOption) *AvatarMutation {
	m := &AvatarMutation{
		config:        c,
		op:            op,
		typ:           TypeAvatar,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAvatarID sets the ID field of the mutation.
func withAvatarID(id string) avatarOption {
	return func(m *AvatarMutation) {
		var (
			err   error
			once  sync.Once
			value *Avatar
		)
		m.oldValue = func(ctx context.Context) (*Avatar, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Avatar.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAvatar sets the old Avatar of the mutation.
func withAvatar(node *Avatar) avatarOption {
	return func(m *AvatarMutation) {
		m.oldValue = func(context.Context) (*Avatar, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AvatarMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AvatarMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Avatar entities.
func (m *AvatarMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AvatarMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AvatarMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Avatar.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetKind sets the "kind" field.
func (m *AvatarMutation) SetKind(i int32) {
	m.kind = &i
	m.addkind = nil
}

// Kind returns the value of the "kind" field in the mutation.
func (m *AvatarMutation) Kind() (r int32, exists bool) {
	v := m.kind
	if v == nil {
		return
	}
	return *v, true
}

// OldKind returns the old "kind" field's value of the Avatar entity.
// If the Avatar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AvatarMutation) OldKind(ctx context.Context) (v *int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKind is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKind requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKind: %w", err)
	}
	return oldValue.Kind, nil
}

// AddKind adds i to the "kind" field.
func (m *AvatarMutation) AddKind(i int32) {
	if m.addkind != nil {
		*m.addkind += i
	} else {
		m.addkind = &i
	}
}

// AddedKind returns the value that was added to the "kind" field in this mutation.
func (m *AvatarMutation) AddedKind() (r int32, exists bool) {
	v := m.addkind
	if v == nil {
		return
	}
	return *v, true
}

// ClearKind clears the value of the "kind" field.
func (m *AvatarMutation) ClearKind() {
	m.kind = nil
	m.addkind = nil
	m.clearedFields[avatar.FieldKind] = struct{}{}
}

// KindCleared returns if the "kind" field was cleared in this mutation.
func (m *AvatarMutation) KindCleared() bool {
	_, ok := m.clearedFields[avatar.FieldKind]
	return ok
}

// ResetKind resets all changes to the "kind" field.
func (m *AvatarMutation) ResetKind() {
	m.kind = nil
	m.addkind = nil
	delete(m.clearedFields, avatar.FieldKind)
}

// SetRelID sets the "rel_id" field.
func (m *AvatarMutation) SetRelID(s string) {
	m.rel_id = &s
}

// RelID returns the value of the "rel_id" field in the mutation.
func (m *AvatarMutation) RelID() (r string, exists bool) {
	v := m.rel_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRelID returns the old "rel_id" field's value of the Avatar entity.
// If the Avatar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AvatarMutation) OldRelID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRelID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRelID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRelID: %w", err)
	}
	return oldValue.RelID, nil
}

// ClearRelID clears the value of the "rel_id" field.
func (m *AvatarMutation) ClearRelID() {
	m.rel_id = nil
	m.clearedFields[avatar.FieldRelID] = struct{}{}
}

// RelIDCleared returns if the "rel_id" field was cleared in this mutation.
func (m *AvatarMutation) RelIDCleared() bool {
	_, ok := m.clearedFields[avatar.FieldRelID]
	return ok
}

// ResetRelID resets all changes to the "rel_id" field.
func (m *AvatarMutation) ResetRelID() {
	m.rel_id = nil
	delete(m.clearedFields, avatar.FieldRelID)
}

// SetAvatar sets the "avatar" field.
func (m *AvatarMutation) SetAvatar(s string) {
	m.avatar = &s
}

// Avatar returns the value of the "avatar" field in the mutation.
func (m *AvatarMutation) Avatar() (r string, exists bool) {
	v := m.avatar
	if v == nil {
		return
	}
	return *v, true
}

// OldAvatar returns the old "avatar" field's value of the Avatar entity.
// If the Avatar object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AvatarMutation) OldAvatar(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAvatar is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAvatar requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAvatar: %w", err)
	}
	return oldValue.Avatar, nil
}

// ClearAvatar clears the value of the "avatar" field.
func (m *AvatarMutation) ClearAvatar() {
	m.avatar = nil
	m.clearedFields[avatar.FieldAvatar] = struct{}{}
}

// AvatarCleared returns if the "avatar" field was cleared in this mutation.
func (m *AvatarMutation) AvatarCleared() bool {
	_, ok := m.clearedFields[avatar.FieldAvatar]
	return ok
}

// ResetAvatar resets all changes to the "avatar" field.
func (m *AvatarMutation) ResetAvatar() {
	m.avatar = nil
	delete(m.clearedFields, avatar.FieldAvatar)
}

// Where appends a list predicates to the AvatarMutation builder.
func (m *AvatarMutation) Where(ps ...predicate.Avatar) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *AvatarMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Avatar).
func (m *AvatarMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AvatarMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.kind != nil {
		fields = append(fields, avatar.FieldKind)
	}
	if m.rel_id != nil {
		fields = append(fields, avatar.FieldRelID)
	}
	if m.avatar != nil {
		fields = append(fields, avatar.FieldAvatar)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AvatarMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case avatar.FieldKind:
		return m.Kind()
	case avatar.FieldRelID:
		return m.RelID()
	case avatar.FieldAvatar:
		return m.Avatar()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AvatarMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case avatar.FieldKind:
		return m.OldKind(ctx)
	case avatar.FieldRelID:
		return m.OldRelID(ctx)
	case avatar.FieldAvatar:
		return m.OldAvatar(ctx)
	}
	return nil, fmt.Errorf("unknown Avatar field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AvatarMutation) SetField(name string, value ent.Value) error {
	switch name {
	case avatar.FieldKind:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKind(v)
		return nil
	case avatar.FieldRelID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRelID(v)
		return nil
	case avatar.FieldAvatar:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAvatar(v)
		return nil
	}
	return fmt.Errorf("unknown Avatar field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AvatarMutation) AddedFields() []string {
	var fields []string
	if m.addkind != nil {
		fields = append(fields, avatar.FieldKind)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AvatarMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case avatar.FieldKind:
		return m.AddedKind()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AvatarMutation) AddField(name string, value ent.Value) error {
	switch name {
	case avatar.FieldKind:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddKind(v)
		return nil
	}
	return fmt.Errorf("unknown Avatar numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AvatarMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(avatar.FieldKind) {
		fields = append(fields, avatar.FieldKind)
	}
	if m.FieldCleared(avatar.FieldRelID) {
		fields = append(fields, avatar.FieldRelID)
	}
	if m.FieldCleared(avatar.FieldAvatar) {
		fields = append(fields, avatar.FieldAvatar)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AvatarMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AvatarMutation) ClearField(name string) error {
	switch name {
	case avatar.FieldKind:
		m.ClearKind()
		return nil
	case avatar.FieldRelID:
		m.ClearRelID()
		return nil
	case avatar.FieldAvatar:
		m.ClearAvatar()
		return nil
	}
	return fmt.Errorf("unknown Avatar nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AvatarMutation) ResetField(name string) error {
	switch name {
	case avatar.FieldKind:
		m.ResetKind()
		return nil
	case avatar.FieldRelID:
		m.ResetRelID()
		return nil
	case avatar.FieldAvatar:
		m.ResetAvatar()
		return nil
	}
	return fmt.Errorf("unknown Avatar field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AvatarMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AvatarMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AvatarMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AvatarMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AvatarMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AvatarMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AvatarMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Avatar unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AvatarMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Avatar edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op            Op
	typ           string
	id            *string
	ancestor_id   *string
	password      *string
	nickname      *string
	ip            *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*User, error)
	predicates    []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id string) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAncestorID sets the "ancestor_id" field.
func (m *UserMutation) SetAncestorID(s string) {
	m.ancestor_id = &s
}

// AncestorID returns the value of the "ancestor_id" field in the mutation.
func (m *UserMutation) AncestorID() (r string, exists bool) {
	v := m.ancestor_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAncestorID returns the old "ancestor_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldAncestorID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAncestorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAncestorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAncestorID: %w", err)
	}
	return oldValue.AncestorID, nil
}

// ClearAncestorID clears the value of the "ancestor_id" field.
func (m *UserMutation) ClearAncestorID() {
	m.ancestor_id = nil
	m.clearedFields[user.FieldAncestorID] = struct{}{}
}

// AncestorIDCleared returns if the "ancestor_id" field was cleared in this mutation.
func (m *UserMutation) AncestorIDCleared() bool {
	_, ok := m.clearedFields[user.FieldAncestorID]
	return ok
}

// ResetAncestorID resets all changes to the "ancestor_id" field.
func (m *UserMutation) ResetAncestorID() {
	m.ancestor_id = nil
	delete(m.clearedFields, user.FieldAncestorID)
}

// SetPassword sets the "password" field.
func (m *UserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *UserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPassword(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ClearPassword clears the value of the "password" field.
func (m *UserMutation) ClearPassword() {
	m.password = nil
	m.clearedFields[user.FieldPassword] = struct{}{}
}

// PasswordCleared returns if the "password" field was cleared in this mutation.
func (m *UserMutation) PasswordCleared() bool {
	_, ok := m.clearedFields[user.FieldPassword]
	return ok
}

// ResetPassword resets all changes to the "password" field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
	delete(m.clearedFields, user.FieldPassword)
}

// SetNickname sets the "nickname" field.
func (m *UserMutation) SetNickname(s string) {
	m.nickname = &s
}

// Nickname returns the value of the "nickname" field in the mutation.
func (m *UserMutation) Nickname() (r string, exists bool) {
	v := m.nickname
	if v == nil {
		return
	}
	return *v, true
}

// OldNickname returns the old "nickname" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldNickname(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNickname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNickname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNickname: %w", err)
	}
	return oldValue.Nickname, nil
}

// ClearNickname clears the value of the "nickname" field.
func (m *UserMutation) ClearNickname() {
	m.nickname = nil
	m.clearedFields[user.FieldNickname] = struct{}{}
}

// NicknameCleared returns if the "nickname" field was cleared in this mutation.
func (m *UserMutation) NicknameCleared() bool {
	_, ok := m.clearedFields[user.FieldNickname]
	return ok
}

// ResetNickname resets all changes to the "nickname" field.
func (m *UserMutation) ResetNickname() {
	m.nickname = nil
	delete(m.clearedFields, user.FieldNickname)
}

// SetIP sets the "ip" field.
func (m *UserMutation) SetIP(s string) {
	m.ip = &s
}

// IP returns the value of the "ip" field in the mutation.
func (m *UserMutation) IP() (r string, exists bool) {
	v := m.ip
	if v == nil {
		return
	}
	return *v, true
}

// OldIP returns the old "ip" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldIP(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIP: %w", err)
	}
	return oldValue.IP, nil
}

// ClearIP clears the value of the "ip" field.
func (m *UserMutation) ClearIP() {
	m.ip = nil
	m.clearedFields[user.FieldIP] = struct{}{}
}

// IPCleared returns if the "ip" field was cleared in this mutation.
func (m *UserMutation) IPCleared() bool {
	_, ok := m.clearedFields[user.FieldIP]
	return ok
}

// ResetIP resets all changes to the "ip" field.
func (m *UserMutation) ResetIP() {
	m.ip = nil
	delete(m.clearedFields, user.FieldIP)
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.ancestor_id != nil {
		fields = append(fields, user.FieldAncestorID)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	if m.nickname != nil {
		fields = append(fields, user.FieldNickname)
	}
	if m.ip != nil {
		fields = append(fields, user.FieldIP)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldAncestorID:
		return m.AncestorID()
	case user.FieldPassword:
		return m.Password()
	case user.FieldNickname:
		return m.Nickname()
	case user.FieldIP:
		return m.IP()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldAncestorID:
		return m.OldAncestorID(ctx)
	case user.FieldPassword:
		return m.OldPassword(ctx)
	case user.FieldNickname:
		return m.OldNickname(ctx)
	case user.FieldIP:
		return m.OldIP(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldAncestorID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAncestorID(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case user.FieldNickname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNickname(v)
		return nil
	case user.FieldIP:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIP(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(user.FieldAncestorID) {
		fields = append(fields, user.FieldAncestorID)
	}
	if m.FieldCleared(user.FieldPassword) {
		fields = append(fields, user.FieldPassword)
	}
	if m.FieldCleared(user.FieldNickname) {
		fields = append(fields, user.FieldNickname)
	}
	if m.FieldCleared(user.FieldIP) {
		fields = append(fields, user.FieldIP)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	switch name {
	case user.FieldAncestorID:
		m.ClearAncestorID()
		return nil
	case user.FieldPassword:
		m.ClearPassword()
		return nil
	case user.FieldNickname:
		m.ClearNickname()
		return nil
	case user.FieldIP:
		m.ClearIP()
		return nil
	}
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldAncestorID:
		m.ResetAncestorID()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	case user.FieldNickname:
		m.ResetNickname()
		return nil
	case user.FieldIP:
		m.ResetIP()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown User edge %s", name)
}
