// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/wzyjerry/auth/internal/biz"
	"github.com/wzyjerry/auth/internal/conf"
	"github.com/wzyjerry/auth/internal/data"
	"github.com/wzyjerry/auth/internal/server"
	"github.com/wzyjerry/auth/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, security *conf.Security, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	registerRepo := data.NewRegisterRepo(dataData, security, logger)
	aliyunHelper := biz.NewAliyunHelper(logger, security)
	registerUsecase := biz.NewRegisterUsecase(registerRepo, security, aliyunHelper, logger)
	registerService := service.NewRegisterService(registerUsecase)
	httpServer := server.NewHTTPServer(confServer, logger, registerService)
	grpcServer := server.NewGRPCServer(confServer, logger, registerService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
