server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  postgres:
    env: AUTH_POSTGRES
  redis:
    env: AUTH_REDIS
    read_timeout: 0.2s
    write_timeout: 0.2s
security:
  password_regex: "^(?=.*?[0-9]+)(?=.*?[a-zA-Z]+).{8,}$"
  aliyun:
    email:
      access_key_id: ALIYUN_EMAIL_ACCESS_KEY_ID
      access_key_secret: ALIYUN_EMAIL_ACCESS_KEY_SECRET
      account_name: aminer-noreply@amail.aminer.cn
      from_alias: Aminer
    sms:
      access_key_id: ALIYUN_SMS_ACCESS_KEY_ID
      access_key_secret: ALIYUN_SMS_ACCESS_KEY_SECRET
      sign_name: AMiner
  oauth:
    github:
      client_id: OAUTH_GITHUB_CLIENT_ID
      client_secret: OAUTH_GITHUB_CLIENT_SECRET
  expiration:
    code: 600s
