// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authenticator is the predicate function for authenticator builders.
type Authenticator func(*sql.Selector)

// Avatar is the predicate function for avatar builders.
type Avatar func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
