server:
  http:
    addr: 0.0.0.0:8888
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9999
    timeout: 5s
data:
  postgres:
    env: AUTH_POSTGRES
  redis:
    env: AUTH_REDIS
    read_timeout: 0.2s
    write_timeout: 0.2s
security:
  password_regex: "^(?=.*?[0-9]+)(?=.*?[a-zA-Z]+).{8,}$"
  private_key: PRIVATE_KEY
  client_id: OAUTH_CLIENT_ID
  
  aliyun:
    email:
      access_key_id: ALIYUN_EMAIL_ACCESS_KEY_ID
      access_key_secret: ALIYUN_EMAIL_ACCESS_KEY_SECRET
      account_name: aminer-noreply@amail.aminer.cn
      from_alias: Aminer
    sms:
      access_key_id: ALIYUN_SMS_ACCESS_KEY_ID
      access_key_secret: ALIYUN_SMS_ACCESS_KEY_SECRET
      sign_name: AMiner
  third_party:
    github:
      client_id: OAUTH_GITHUB_CLIENT_ID
      client_secret: OAUTH_GITHUB_CLIENT_SECRET
    microsoft:
      client_id: OAUTH_MICROSOFT_CLIENT_ID
      client_secret: OAUTH_MICROSOFT_CLIENT_SECRET
      redirect_uri: http://localhost:8000/oauth/microsoft
  expiration:
    code: 600s
    token_extend: 300s
    access_token: 3600s
    refresh_token: 7776000s
