// Code generated by windranger, DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.6
// source: internal/ent/schema/authenticatorNested/authenticatorNested.proto

package authenticatorNested

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 认证器类型
type Kind int32

const (
	Kind_KIND_UNSET   Kind = 0  // 保留字：未设置
	Kind_KIND_ACCOUNT Kind = 1  // 用户账户
	Kind_KIND_EMAIL   Kind = 2  // 邮箱
	Kind_KIND_PHONE   Kind = 3  // 手机
	Kind_KIND_CLEAR   Kind = -1 // 保留字：清空
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0:  "KIND_UNSET",
		1:  "KIND_ACCOUNT",
		2:  "KIND_EMAIL",
		3:  "KIND_PHONE",
		-1: "KIND_CLEAR",
	}
	Kind_value = map[string]int32{
		"KIND_UNSET":   0,
		"KIND_ACCOUNT": 1,
		"KIND_EMAIL":   2,
		"KIND_PHONE":   3,
		"KIND_CLEAR":   -1,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{0}
}

// 用户账户认证器
type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username *string `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"` // 账户名(*)
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

// 锚
type Anchor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *Account `protobuf:"bytes,1,opt,name=account,proto3,oneof" json:"account,omitempty"` // 用户账户认证器
	Email   *Email   `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`     // 邮箱认证器
	Phone   *Phone   `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`     // 手机认证器
}

func (x *Anchor) Reset() {
	*x = Anchor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Anchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anchor) ProtoMessage() {}

func (x *Anchor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anchor.ProtoReflect.Descriptor instead.
func (*Anchor) Descriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{1}
}

func (x *Anchor) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Anchor) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *Anchor) GetPhone() *Phone {
	if x != nil {
		return x.Phone
	}
	return nil
}

// 认证器
type Authenticator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                    // 主键
	UserId *string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`              // 用户ID
	Kind   *Kind   `protobuf:"varint,3,opt,name=kind,proto3,enum=authenticatorNested.Kind,oneof" json:"kind,omitempty"` // 认证器类型
	Anchor *Anchor `protobuf:"bytes,4,opt,name=anchor,proto3,oneof" json:"anchor,omitempty"`                            // 锚
}

func (x *Authenticator) Reset() {
	*x = Authenticator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authenticator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator) ProtoMessage() {}

func (x *Authenticator) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator.ProtoReflect.Descriptor instead.
func (*Authenticator) Descriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{2}
}

func (x *Authenticator) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Authenticator) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *Authenticator) GetKind() Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Kind_KIND_UNSET
}

func (x *Authenticator) GetAnchor() *Anchor {
	if x != nil {
		return x.Anchor
	}
	return nil
}

// 邮箱认证器
type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *string `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"` // 邮箱(*)
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{3}
}

func (x *Email) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

// 手机认证器
type Phone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone *string `protobuf:"bytes,1,opt,name=phone,proto3,oneof" json:"phone,omitempty"` // 手机号(*)
}

func (x *Phone) Reset() {
	*x = Phone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP(), []int{4}
}

func (x *Phone) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

var File_internal_ent_schema_authenticatorNested_authenticatorNested_proto protoreflect.FileDescriptor

var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDesc = []byte{
	0x0a, 0x41, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x6e, 0x74, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22, 0x37, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0xd3, 0x01, 0x0a, 0x06, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x48, 0x01, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01,
	0x12, 0x35, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x48, 0x02, 0x52, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0xd7, 0x01, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1c,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x48, 0x02, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x38, 0x0a, 0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x48, 0x03, 0x52,
	0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69,
	0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x6e, 0x63, 0x68, 0x6f,
	0x72, 0x22, 0x2c, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x2c, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2a, 0x61, 0x0a,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e,
	0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x41, 0x43,
	0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x0a, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x43, 0x4c, 0x45, 0x41, 0x52, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01,
	0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77,
	0x7a, 0x79, 0x6a, 0x65, 0x72, 0x72, 0x79, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescOnce sync.Once
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescData = file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDesc
)

func file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescGZIP() []byte {
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescOnce.Do(func() {
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescData)
	})
	return file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDescData
}

var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_goTypes = []interface{}{
	(Kind)(0),             // 0: authenticatorNested.Kind
	(*Account)(nil),       // 1: authenticatorNested.Account
	(*Anchor)(nil),        // 2: authenticatorNested.Anchor
	(*Authenticator)(nil), // 3: authenticatorNested.Authenticator
	(*Email)(nil),         // 4: authenticatorNested.Email
	(*Phone)(nil),         // 5: authenticatorNested.Phone
}
var file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_depIdxs = []int32{
	1, // 0: authenticatorNested.Anchor.account:type_name -> authenticatorNested.Account
	4, // 1: authenticatorNested.Anchor.email:type_name -> authenticatorNested.Email
	5, // 2: authenticatorNested.Anchor.phone:type_name -> authenticatorNested.Phone
	0, // 3: authenticatorNested.Authenticator.kind:type_name -> authenticatorNested.Kind
	2, // 4: authenticatorNested.Authenticator.anchor:type_name -> authenticatorNested.Anchor
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_init() }
func file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_init() {
	if File_internal_ent_schema_authenticatorNested_authenticatorNested_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Anchor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authenticator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_goTypes,
		DependencyIndexes: file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_depIdxs,
		EnumInfos:         file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_enumTypes,
		MessageInfos:      file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_msgTypes,
	}.Build()
	File_internal_ent_schema_authenticatorNested_authenticatorNested_proto = out.File
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_rawDesc = nil
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_goTypes = nil
	file_internal_ent_schema_authenticatorNested_authenticatorNested_proto_depIdxs = nil
}
